// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_phaoIGUQGgwMD6C49_Jv9I51wVD0y8',
    appId: '1:914371335845:android:1e6e0a3d3340bb97fb1f4c',
    messagingSenderId: '914371335845',
    projectId: 'hotel-app-5b931',
    storageBucket: 'hotel-app-5b931.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2irjwzut0Cg8nf057Is5egxAiBvgBOE',
    appId: '1:914371335845:web:b2d1b2a9cb2eba0dfb1f4c',
    messagingSenderId: '914371335845',
    projectId: 'hotel-app-5b931',
    authDomain: 'hotel-app-5b931.firebaseapp.com',
    storageBucket: 'hotel-app-5b931.firebasestorage.app',
    measurementId: 'G-9K92ZMT3F2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnosj-TDXOm5VD-1W-_TLUgzjLVOQa7UE',
    appId: '1:914371335845:ios:ec884c01dd8ec71bfb1f4c',
    messagingSenderId: '914371335845',
    projectId: 'hotel-app-5b931',
    storageBucket: 'hotel-app-5b931.firebasestorage.app',
    iosBundleId: 'com.example.hotelGuide',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnosj-TDXOm5VD-1W-_TLUgzjLVOQa7UE',
    appId: '1:914371335845:ios:ec884c01dd8ec71bfb1f4c',
    messagingSenderId: '914371335845',
    projectId: 'hotel-app-5b931',
    storageBucket: 'hotel-app-5b931.firebasestorage.app',
    iosBundleId: 'com.example.hotelGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN2irjwzut0Cg8nf057Is5egxAiBvgBOE',
    appId: '1:914371335845:web:f63cd44298e0b6a7fb1f4c',
    messagingSenderId: '914371335845',
    projectId: 'hotel-app-5b931',
    authDomain: 'hotel-app-5b931.firebaseapp.com',
    storageBucket: 'hotel-app-5b931.firebasestorage.app',
    measurementId: 'G-JLKJ3FLTSK',
  );

}